### ISSUE TITLE
Install failed on macOS Mojave

### ISSUE THREAD

**Issue by rapodaca** [thesketh/oxmol#6]
Following the instructions [here](https://oxmol.readthedocs.io/en/latest/installation.html), I was able to compile oxmol. The install command did not generate errors;

```console
python3 --version
Python 3.7.7

pip3 install 3
Collecting 3
  Downloading 3-0.0.0-py3-none-any.whl (1.6 kB)
Installing collected packages: 3
Successfully installed 3-0.0.0
```

Attempts to use a more specific `RELEVANT_VERSION` (e.g., 3.7.7) failed:

```console
pip3 install 3.7.7
ERROR: Could not find a version that satisfies the requirement 3.7.7 (from versions: none)
ERROR: No matching distribution found for 3.7.7
```

Trying anyway:

```python
python3
Python 3.7.7 (default, Mar 10 2020, 15:43:03) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from oxmol import AtomSpec, BondSpec, Molecule
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'oxmol'
```

Being new to this, the problem may be in my system configuration. Any ideas for how to proceed?

**Comment by thesketh** [comment]
Whoops, the instructions made perfect sense to me at the time but I can see why they're unclear! I've updated them to be more clear but they might not be finished compiling yet.

`maturin build --release` should generate some wheels in ``target/wheels``, but it creates a wheel for each version of Python that it finds in the PATH (so on my Ubuntu system I end up with a wheel for the system Python and a wheel for the conda Python). By ``RELEVANT_VERSION`` I meant the most relevant wheel from this folder.

If you're running Python 3.7, you probably want the wheel that starts with `oxmol-0.1.0-cp37-...` the full name will be something like `oxmol-0.1.0-cp37-cp37m-macosx_10_13_intel.whl`. You should be able to pip install this file.

**Comment by thesketh** [comment]
I will note that it shouldn't be this complicated, after I've put together the automated tests and worked out CI and a good build process I'll make sure it's listed on PyPI and can be installed with a simple `pip install oxmol`

**Comment by thesketh** [comment]
I've uploaded some binary releases to the test PyPI now, so it should be possible to run the following command to install:

```pip install --index-url https://test.pypi.org/simple/ oxmol```

Please feel free to reopen if you run into any other issues
